---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.6.0
  customize:
    natdnshostresolver1: "on"
    memory: 2048
provisioner: chef_zero

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode_ubuntu-14.04_chef-provisionerless
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
- name: default
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_zookeeper::test]
    - recipe[optoro_zookeeper::default]
  attributes:
    apt:
      compile_time_update: true

- name: consul
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_zookeeper::test]
    - recipe[optoro_zookeeper::default]
  attributes:
    apt:
      compile_time_update: true
    optoro_consul:
      register_consul_service: true
      service:
        checks:
          - { script: 'echo true', interval: '5s' }
