---
# Set ~/.aws/credentials file for access keys
# $AWS_SSH_KEY_ID to specify what key to use
driver:
  name: ec2
  require_chef_omnibus: 12.6.0
  security_group_ids: ["sg-68ce330c"]
  subnet_id: subnet-2f5f9f04
  region: us-east-1
  availability_zone: e
  instance_type: m3.medium
  image_id: ami-74b3e11c
  iam_profile_name: TestKitchenRole
  associate_public_ip: false
  interface: private

transport:
  ssh_key: ~/.ssh/kp-2011-05-02.pem
  username: ubuntu

provisioner: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
- name: default
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_zookeeper::test]
    - recipe[optoro_zookeeper::default]
  attributes:
    apt:
      compile_time_update: true

- name: consul
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_aptly::repos]
    - recipe[optoro_logstash::default]
    - recipe[optoro_zookeeper::test]
    - recipe[optoro_zookeeper::default]
  attributes:
    apt:
      compile_time_update: true
    optoro_consul:
      register_consul_service: true
      service:
        checks:
          - { script: 'echo true', interval: '5s' }
