PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  TrailingWhitespace:
    enabled: true

  Foodcritic:
    enabled: true

  ShellCheck:
    enabled: false

  CookbookVersion:
    description: 'Checking for updated cookbook version'
    enabled: true
